/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonsSalonIdRouteImport } from './routes/salons.$salonId'
import { Route as BookSalonIdRouteImport } from './routes/book.$salonId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsSalonIdRoute = SalonsSalonIdRouteImport.update({
  id: '/salons/$salonId',
  path: '/salons/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSalonIdRoute = BookSalonIdRouteImport.update({
  id: '/book/$salonId',
  path: '/book/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/api/chat': typeof ApiChatRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/partner'
    | '/api/chat'
    | '/book/$salonId'
    | '/salons/$salonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/partner' | '/api/chat' | '/book/$salonId' | '/salons/$salonId'
  id:
    | '__root__'
    | '/'
    | '/partner'
    | '/api/chat'
    | '/book/$salonId'
    | '/salons/$salonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartnerRoute: typeof PartnerRoute
  ApiChatRoute: typeof ApiChatRoute
  BookSalonIdRoute: typeof BookSalonIdRoute
  SalonsSalonIdRoute: typeof SalonsSalonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$salonId': {
      id: '/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/salons/$salonId'
      preLoaderRoute: typeof SalonsSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$salonId': {
      id: '/book/$salonId'
      path: '/book/$salonId'
      fullPath: '/book/$salonId'
      preLoaderRoute: typeof BookSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartnerRoute: PartnerRoute,
  ApiChatRoute: ApiChatRoute,
  BookSalonIdRoute: BookSalonIdRoute,
  SalonsSalonIdRoute: SalonsSalonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
